repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: flake8
    -   id: sort-simple-yaml
    -   id: check-executables-have-shebangs
    -   id: detect-aws-credentials
    -   id: debug-statements
    -   id: check-xml
    -   id: check-symlinks
    -   id: check-merge-conflict
    -   id: pretty-format-json --autofix --indent 4
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.7.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.2.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    hooks:
    -   id: check-bash-syntax
        name: Check Shell scripts syntax corectness
        language: system
        entry: bash -n
        files: \.sh$
